name: goteira-rust
base: core22
version: '0.1.0'
summary: Rust version of Goteira connectivity tester
description: |
  Goteira is a tool to test network connectivity using ping and optionally mtr (traceroute).
  This is the high-performance Rust version.

grade: stable
confinement: strict

parts:
  goteira:
    plugin: rust
    source: ../../
    build-packages:
      - pkg-config
      - libssl-dev
    stage-packages:
      - iputils-ping
      - mtr-tiny

apps:
  goteira-rust:
    command: bin/goteira
    plugs:
      - network
      - network-bind
      - network-observe
